version: '3'
services:
  postgres:
    image: postgres:12-alpine
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - 'env'
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: 'redis:5-alpine'
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - redis:/var/lib/redis/data
    env_file:
      - 'env'

  app:
    build: .
    entrypoint: ./docker-entrypoint.sh
    command: /bin/bash -c "bundle exec rails s -b 0.0.0.0 -p 3000"
    volumes:
        - .:/app
        - gems:/bundle
    ports:
        - "3000:3000"
    env_file:
        - 'env'
    depends_on:
        - postgres
        - redis
    tty: true
    stdin_open: true

volumes:
  redis:
  postgres:
  gems: